/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Spark brand palette
        spark: {
          crimson:  '#FF2D55',
          rose:     '#FF6CAE',
          violet:   '#BF5AF2',
          purple:   '#9B59D0',
          gold:     '#FFD700',
          dark:     '#1C1C2E',
          darker:   '#0F0F1A',
          card:     '#16162A',
          glass:    'rgba(255,255,255,0.06)',
          border:   'rgba(255,255,255,0.1)',
        },
      },
      fontFamily: {
        display: ['Playfair Display', 'Georgia', 'serif'],
        sans:    ['DM Sans', 'system-ui', 'sans-serif'],
        mono:    ['JetBrains Mono', 'monospace'],
      },
      backgroundImage: {
        'gradient-spark':      'linear-gradient(135deg, #FF2D55 0%, #BF5AF2 100%)',
        'gradient-spark-soft': 'linear-gradient(135deg, #FF6CAE 0%, #BF5AF2 100%)',
        'gradient-dark':       'linear-gradient(180deg, #1C1C2E 0%, #0F0F1A 100%)',
        'gradient-card':       'linear-gradient(145deg, #1E1E32 0%, #16162A 100%)',
        'gradient-gold':       'linear-gradient(135deg, #FFD700 0%, #FF9500 100%)',
        'gradient-match':      'radial-gradient(ellipse at center, rgba(255,45,85,0.3) 0%, transparent 70%)',
      },
      boxShadow: {
        'spark':    '0 0 20px rgba(255,45,85,0.4)',
        'violet':   '0 0 20px rgba(191,90,242,0.4)',
        'gold':     '0 0 20px rgba(255,215,0,0.4)',
        'card':     '0 8px 32px rgba(0,0,0,0.4)',
        'card-hover': '0 16px 48px rgba(255,45,85,0.2)',
        'glass':    '0 4px 24px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.1)',
        'inner-glow': 'inset 0 0 20px rgba(255,45,85,0.1)',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      animation: {
        'float':        'float 6s ease-in-out infinite',
        'pulse-spark':  'pulse-spark 2s ease-in-out infinite',
        'swipe-left':   'swipe-left 0.4s ease-out forwards',
        'swipe-right':  'swipe-right 0.4s ease-out forwards',
        'match-pop':    'match-pop 0.6s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'heart-burst':  'heart-burst 0.5s ease-out forwards',
        'slide-up':     'slide-up 0.4s cubic-bezier(0.16,1,0.3,1) forwards',
        'slide-down':   'slide-down 0.4s cubic-bezier(0.16,1,0.3,1) forwards',
        'fade-in':      'fade-in 0.3s ease forwards',
        'shimmer':      'shimmer 2s linear infinite',
        'typing':       'typing 1.5s ease-in-out infinite',
        'bounce-soft':  'bounce-soft 0.6s cubic-bezier(0.34,1.56,0.64,1)',
      },
      keyframes: {
        float:         { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        'pulse-spark': { '0%,100%': { boxShadow: '0 0 0 0 rgba(255,45,85,0.4)' }, '50%': { boxShadow: '0 0 0 12px rgba(255,45,85,0)' } },
        'swipe-left':  { to: { transform: 'translateX(-150%) rotate(-30deg)', opacity: '0' } },
        'swipe-right': { to: { transform: 'translateX(150%) rotate(30deg)', opacity: '0' } },
        'match-pop':   { '0%': { transform: 'scale(0)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        'heart-burst': { '0%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.5)' }, '100%': { transform: 'scale(1)' } },
        'slide-up':    { from: { transform: 'translateY(20px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        'slide-down':  { from: { transform: 'translateY(-20px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        'fade-in':     { from: { opacity: '0' }, to: { opacity: '1' } },
        shimmer:       { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        typing:        { '0%,100%': { opacity: '0.3' }, '50%': { opacity: '1' } },
        'bounce-soft': { '0%': { transform: 'scale(0.8)' }, '60%': { transform: 'scale(1.1)' }, '100%': { transform: 'scale(1)' } },
      },
      backdropBlur: { xs: '2px' },
    },
  },
  plugins: [],
};
